"""Entity metadata accessors, keyed by (time, entity) index + SpatialLevel.

Reads the **bundled** metadata assets (``metadata/data/*.parquet``, generated by
``scripts/build_entity_metadata.py`` — register C-22, ADR-018): no service call
at render time, reports render offline/air-gapped. The tables are
**entity-keyed** and the accessors **broadcast over whatever months the caller's
index carries** — future (forecast) months resolve by construction. This
replaces the pre-C-22 live viewser fetch, whose exact ``(month_id, entity_id)``
keying silently NaN'd every label for months absent from the source table
(emptying CM maps via the geometry merge — see epic #204).

Failure semantics (ADR-008): a missing bundle fails loud with a regeneration
hint; entities absent from the bundle degrade visibly (NaN label + one
aggregated warning) because a lookup table must not veto the report (ADR-018);
a frame whose entities are *all* unknown raises — that is a wrong-table/level
error, not sparse coverage.
"""

from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd
from views_frames import SpatialLevel

logger = logging.getLogger(__name__)

_DATA_DIR = Path(__file__).parent / "data"

# Memoised bundled tables, keyed by filename stem. Loading is idempotent, so a
# double-load race between threads is benign (last write wins with identical
# content) — no lock needed.
_TABLE_CACHE: dict[str, pd.DataFrame] = {}

# Memoised INDEXED lookup Series derived from the tables (#251): rebuilding
# `set_index(...)` over the 66k-row priogrid table on every accessor call was
# pure repeated work. Same benign-race reasoning as above.
_SERIES_CACHE: dict[str, pd.Series] = {}


def _reset_metadata_cache() -> None:
    """Test hook: clear the memoised tables AND derived Series (module-global
    state hygiene — both caches, or a stale Series would survive a reload)."""
    _TABLE_CACHE.clear()
    _SERIES_CACHE.clear()


def metadata_snapshot_date() -> str | None:
    """The bundle's snapshot timestamp (stamp.json), for report provenance —
    staleness is observable in every artifact (register C-112) without a CI
    time-bomb. Returns None if the stamp is absent/unreadable (provenance
    omits None values; the accessors themselves still fail loud)."""
    try:
        import json

        stamp = json.loads((_DATA_DIR / "stamp.json").read_text())
        return str(stamp["snapshot_utc"])
    except (OSError, ValueError, KeyError):
        return None


def _load_table(stem: str) -> pd.DataFrame:
    cached = _TABLE_CACHE.get(stem)
    if cached is not None:
        return cached
    path = _DATA_DIR / f"{stem}.parquet"
    if not path.exists():
        raise FileNotFoundError(
            f"Bundled metadata asset missing: {path}. Regenerate the bundle with "
            "scripts/build_entity_metadata.py (requires viewser, dev-time only) "
            "and commit the assets."
        )
    df = pd.read_parquet(path)
    _TABLE_CACHE[stem] = df
    return df


def _indexed_series(cache_key: str, stem: str, key: str, col: str) -> pd.Series:
    cached = _SERIES_CACHE.get(cache_key)
    if cached is None:
        cached = _load_table(stem).set_index(key)[col]
        _SERIES_CACHE[cache_key] = cached
    return cached


def _country_isoab() -> pd.Series:
    """country_id → isoab (may be NaN where the source has no ISO code, e.g.
    Kosovo — declared in stamp.json)."""
    return _indexed_series("country_isoab", "country", "country_id", "isoab")


def _country_name() -> pd.Series:
    """country_id → name."""
    return _indexed_series("country_name", "country", "country_id", "name")


def _priogrid_country() -> pd.Series:
    """priogrid_id → country_id (latest known assignment — declared limitation,
    see stamp.json ``priogrid_semantics``)."""
    return _indexed_series("priogrid_country", "priogrid", "priogrid_id", "country_id")


def _entity_country_ids(index: pd.MultiIndex, level: SpatialLevel) -> pd.Series:
    """The country_id for each row of ``index`` — the identity join underneath
    both accessors. CM: the entity level *is* the country_id. PGM: resolved via
    the bundled cell→country assignment. Raises if *no* entity resolves."""
    entity_name = level.index_names[1]
    entities = pd.Series(index.get_level_values(entity_name), dtype="int64")
    if level == SpatialLevel.CM:
        known = _country_isoab().index
        country_ids = entities.where(entities.isin(known))
    else:
        country_ids = entities.map(_priogrid_country())
    unknown = entities[country_ids.isna()].unique()
    if len(unknown) == len(entities.unique()) and len(unknown) > 0:
        raise ValueError(
            f"No {entity_name} in this frame is present in the bundled metadata "
            f"({len(unknown)} unknown, e.g. {sorted(unknown)[:5]}) — wrong level, "
            "wrong id coding, or a stale bundle. Regenerate via "
            "scripts/build_entity_metadata.py if coverage has expanded."
        )
    if len(unknown) > 0:
        logger.warning(
            "%d %s value(s) not in the bundled metadata (e.g. %s) — their labels "
            "render as missing. If coverage has expanded, regenerate via "
            "scripts/build_entity_metadata.py.",
            len(unknown),
            entity_name,
            sorted(unknown)[:5],
        )
    return country_ids


# ── Index-keyed accessors (frame-native edge) ──────────────────────────────


def get_labels_for_index(
    index: pd.MultiIndex, level: SpatialLevel, with_id: bool = False
) -> pd.DataFrame:
    """BOTH labels — ``isoab`` and ``name`` — for the rows of ``index`` at
    ``level``, from ONE cell→country resolution (#251: isoab and name are two
    labels of the same fact; resolving it twice per render was pure repeated
    work). Entity-keyed, month-broadcast; unknown entities degrade to NaN with
    the single aggregated warning; an all-unknown frame raises (unchanged
    failure semantics).

    With ``with_id`` the name is ``"{country_id} - {name}"`` (the legacy
    label shape).
    """
    country_ids = _entity_country_ids(index, level)
    isoab = country_ids.map(_country_isoab()).to_numpy()
    names = country_ids.map(_country_name())
    if with_id:
        combined = (
            country_ids.astype("Int64").astype("string")
            + " - "
            + names.astype("string")
        )
        name_values = combined.to_numpy(dtype=object)
    else:
        name_values = names.to_numpy()
    return pd.DataFrame({"isoab": isoab, "name": name_values}, index=index)


def get_isoab_for_index(index: pd.MultiIndex, level: SpatialLevel) -> pd.DataFrame:
    """ISO codes for the rows of ``index`` at ``level`` — entity-keyed,
    broadcast over all requested months (future months resolve). Thin wrapper
    over :func:`get_labels_for_index` (one column of the same resolution)."""
    return get_labels_for_index(index, level)[["isoab"]]


def get_name_for_index(
    index: pd.MultiIndex, level: SpatialLevel, with_id: bool = False
) -> pd.DataFrame:
    """Country names for the rows of ``index`` at ``level``.

    With ``with_id`` the value is ``"{country_id} - {name}"`` (both levels),
    matching the legacy label shape. Entity-keyed, month-broadcast. Thin
    wrapper over :func:`get_labels_for_index`.
    """
    return get_labels_for_index(index, level, with_id=with_id)[["name"]]
