"""Falsification stubs — claim: "the uniform-lattice fix is 100% sufficiently specified".

Generated by /falsify (2026-07-15). Verdict: FALSIFIED — the spec fixes the
geometry but ignores the contracts calibrated to the SPARSE representation.
Each stub encodes what the CORRECTED spec must satisfy; each is
``xfail(strict=False)`` so CI stays green until the fix story lands, then the
markers are dropped to lock the property in (repo convention:
test_falsify_views_frames_integration.py). NOT committed until the fix story
is scoped — findings route through /register-risk first.
"""

from __future__ import annotations

import base64
import io
from unittest.mock import MagicMock, patch

import numpy as np
import pandas as pd
import pytest

try:
    from views_frames import PredictionFrame, SpatialLevel, SpatioTemporalIndex

    from views_reporting.mapping.mapping import MappingModule
except ImportError:
    pytest.skip("views_frames not installed", allow_module_level=True)

TARGET = "pred_x"


def _pgm_module():
    mock_gdf = MagicMock()
    mock_gdf.columns = ["gid", "xcoord", "ycoord", "col", "row", "geometry"]
    with patch("views_reporting.mapping.mapping.gpd.read_file", return_value=mock_gdf):
        idx = SpatioTemporalIndex(
            time=np.array([528], dtype=np.int64),
            unit=np.array([1], dtype=np.int64),
            level=SpatialLevel.PGM,
        )
        return MappingModule(
            frame=PredictionFrame(np.array([[1.0]], dtype=np.float32), idx),
            level=SpatialLevel.PGM,
            target_column=TARGET,
        )


def _gapped_mdf(module, times=(528,)):
    """The Marion-class fixture: a coastal block + ONE isolated far-south cell."""
    coords = [(-34.75, 19.25), (-34.75, 19.75), (-34.25, 19.25), (-34.25, 19.75),
              (-46.75, 37.75)]  # the isolated cell, 12 degrees south
    rows = []
    for t in times:
        for i, (lat, lon) in enumerate(coords, start=1):
            rows.append({
                module._location_col: i, module._time_id: t, TARGET: float(i),
                "xcoord": lon, "ycoord": lat, "row": 0, "col": 0,
            })
    return pd.DataFrame(rows)


@pytest.mark.xfail(
    strict=False,
    reason="F2 (HARD): the raster budget guard measures len(mapping_dataframe) "
    "(data rows), but under the uniform-lattice fix the payload driver is "
    "bounding-box cells x frames. A sparse-but-spread frame must be refused or "
    "escalated on the LATTICE size, not silently rendered with an exploded z. "
    "Tracked for the fix story (epic follow-up to C-207/#215 diagnosis).",
)
def test_raster_budget_is_keyed_to_lattice_size_not_data_rows():
    m = _pgm_module()
    mdf = _gapped_mdf(m)  # 5 data rows; bbox = 25 lat-steps x 38 lon-steps
    # Post-fix contract: the guard quantity must reflect the rendered lattice.
    # A frame whose LATTICE exceeds the budget must raise even when len(mdf)
    # is tiny. (Encoded with a tiny budget to make the property testable.)
    with pytest.raises(ValueError, match="raster"):
        m.plot_map(mdf, TARGET, interactive=True, as_html=True,
                   raster=True, max_raster_cell_frames=20)


@pytest.mark.xfail(
    strict=False,
    reason="F4 (SOFT): NaN filler cells must not offer hover popups "
    "(hoverongaps=False) — post-fix the ocean is most of the lattice.",
)
def test_raster_filler_cells_have_no_hover():
    m = _pgm_module()
    fig = m.plot_map(_gapped_mdf(m), TARGET, interactive=True, as_html=False,
                     raster=True)
    assert fig.data[0].hoverongaps is False


@pytest.mark.xfail(
    strict=False,
    reason="F3 (LATENT, current bug): _plot_image_map spreads the row array "
    "evenly across the lat extent (imshow semantics), so a gapped lattice "
    "misplaces EVERY cell and desyncs the coastline overlay. The fix must "
    "place cells at true coordinates (uniform lattice).",
)
def test_png_places_gapped_lattice_cells_at_true_latitude():
    m = _pgm_module()
    m._coastline_cache = (np.array([0.0, np.nan]), np.array([0.0, np.nan]))
    html = m._plot_image_map(_gapped_mdf(m), TARGET)
    png = base64.b64decode(html.split("base64,", 1)[1].split('"', 1)[0])
    import matplotlib.image as mpimg

    img = mpimg.imread(io.BytesIO(png))
    # Post-fix property: the coastal block occupies the TOP ~4% of the data
    # extent (0.5 to 1.0 of 12.5 deg), not the top two-thirds that even-spread
    # rows produce. Assert the vertical span of coloured (non-white) pixels in
    # the map axes is consistent with true-coordinate placement: the coloured
    # rows must NOT extend below 40% of the image height (loose bound chosen
    # to fail under today's even-spread behaviour and pass under the fix).
    rgb = img[..., :3]
    coloured = (rgb < 0.85).any(axis=2)
    rows_with_colour = np.where(coloured.any(axis=1))[0]
    assert rows_with_colour.max() < img.shape[0] * 0.4
