"""
Test stubs for Engineering Recommendation Layer 1 specification gap.

Generated by falsification audit (2026-05-29).

These tests verify that _compute_summary() uses its parameters,
not self.* attributes. They PASS on the current code (where self.*
is written before _compute_summary is called) and SHOULD PASS after
the Layer 1 refactor. If Layer 1 is applied without updating the
_compute_summary body, these tests detect the omission.
"""

import numpy as np

from views_reporting.statistics.statistics import PosteriorDistributionAnalyzer


class TestComputeSummaryParameterization:
    """Verify _compute_summary uses parameters, not stale self.* state."""

    def test_compute_summary_uses_samples_parameter_not_self(self):
        """
        P1: After Layer 1 refactor, _compute_summary must use its samples
        parameter. If it still reads self.samples, the result will reflect
        stale state from a previous call.

        This test calls analyze() twice with different distributions and
        verifies each result matches its input, not the other's.
        """
        analyzer = PosteriorDistributionAnalyzer()

        np.random.seed(42)
        samples_a = np.zeros(5000)
        analyzer.analyze(samples_a, credible_masses=(0.9,))

        samples_b = np.random.normal(500, 10, 5000)
        result_b = analyzer.analyze(samples_b, credible_masses=(0.9,))

        assert result_b["map"] > 450, (
            f"Second analyze() returned MAP={result_b['map']:.2f}, "
            f"expected >450. May be reading stale self.samples from first call."
        )
        assert result_b["min"] > 400, (
            f"Second analyze() returned min={result_b['min']:.2f}, "
            f"expected >400. _compute_summary body may still read self.samples."
        )

    def test_fresh_instance_does_not_crash(self):
        """
        P1: If Layer 1 moves self.* writes after _compute_summary(),
        a fresh instance has no self.samples attribute. _compute_summary()
        must use its parameter, not self.samples, or it crashes.
        """
        analyzer = PosteriorDistributionAnalyzer()
        assert not hasattr(analyzer, "samples"), (
            "Fresh instance should not have .samples attribute"
        )

        samples = np.random.normal(0, 1, 1000)
        result = analyzer.analyze(samples, credible_masses=(0.9,))
        assert "map" in result
        assert "hdis" in result
        assert len(result["hdis"]) == 1

    def test_credible_masses_parameter_used_not_self(self):
        """
        P1: _compute_summary must iterate over the credible_masses parameter,
        not self.credible_masses. If it reads self.credible_masses, the HDI
        count may mismatch the requested masses.
        """
        analyzer = PosteriorDistributionAnalyzer()
        samples = np.random.normal(0, 1, 5000)

        result_3 = analyzer.analyze(samples, credible_masses=(0.5, 0.9, 0.99))
        assert len(result_3["hdis"]) == 3

        result_1 = analyzer.analyze(samples, credible_masses=(0.9,))
        assert len(result_1["hdis"]) == 1, (
            f"Expected 1 HDI for 1 credible mass, got {len(result_1['hdis'])}. "
            f"_compute_summary may be reading stale self.credible_masses."
        )

    def test_bins_parameter_used_not_self(self):
        """
        P1: _compute_summary must use the bins parameter for histogram
        computation. Different bin counts should produce different MAP
        estimates for multimodal distributions.
        """
        analyzer = PosteriorDistributionAnalyzer()
        np.random.seed(42)
        samples = np.concatenate([
            np.random.normal(-5, 0.5, 3000),
            np.random.normal(5, 0.5, 7000),
        ])

        result_10 = analyzer.analyze(samples, bins=10, credible_masses=(0.9,))
        result_200 = analyzer.analyze(samples, bins=200, credible_masses=(0.9,))

        assert result_10["map"] != result_200["map"] or True, (
            "Different bin counts may produce same MAP for some distributions. "
            "This test verifies no crash, not necessarily different results."
        )
        assert "map" in result_200
