"""Packaging invariants surfaced by the hatchling+uv migration falsification audit.

These guard the build-tooling decisions (ADR-014, superseding ADR-013): the
declared Python envelope (platform-wide `>=3.11,<3.15` since 2026-08-02 —
tested-on stays 3.11; C-36), the Linux/macOS resolution scope, and the removal
of the unused `views-transformation-library` direct dependency. Generated by
/falsify; envelope invariant rewritten with the C-36 decision reversal.
"""

import sys
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover
    import tomli as tomllib

PYPROJECT = Path(__file__).resolve().parent.parent / "pyproject.toml"


def _pyproject():
    return tomllib.loads(PYPROJECT.read_text())


def test_requires_python_matches_platform_envelope():
    """Decision 2026-08-02 (C-36 update, supersedes the old below-3.12 cap):
    declare the PLATFORM envelope ``>=3.11,<3.15`` — the same range
    views-pipeline-core 3.0.0 and views-evaluation declare — so this repo does
    not under-declare and force resolver exclusion of views-reporting in 3.12+
    platform environments. Practical 3.12-3.14 installs still fail LOUDLY at
    build time in vpc's transitive chain (ingester3 2.1.1 -> levenshtein
    0.20.9, no cp312+ wheel, sdist build broken — re-verified 2026-08-02);
    that fix is upstream and does not change our declared envelope. Tested-on
    stays 3.11 (CI). If the envelope moves, move it deliberately WITH the
    platform, not unilaterally."""
    rp = _pyproject()["project"]["requires-python"].replace(" ", "")
    assert rp == ">=3.11,<3.15", (
        f"requires-python must equal the platform envelope '>=3.11,<3.15' "
        f"(vpc 3.0.0 / views-evaluation), got {rp!r}"
    )


def test_resolution_scoped_to_linux_and_macos():
    """viewser -> docker -> pywin32 makes universal resolution fail on Windows.
    uv environments must scope to the supported platforms (Linux + macOS)."""
    envs = " ".join(_pyproject().get("tool", {}).get("uv", {}).get("environments", []))
    assert "linux" in envs and "darwin" in envs and "win32" not in envs, (
        f"uv environments must be scoped to linux+darwin, got {envs!r}"
    )


def test_no_unused_transformation_library_dependency():
    """FALSIFICATION P3: views-transformation-library is never imported in
    views_reporting and is already pulled transitively via views-pipeline-core,
    so it must not be a *direct* dependency. FAILS until the phantom dep is
    removed from pyproject and the lockfile regenerated."""
    deps = _pyproject()["project"]["dependencies"]
    offenders = [d for d in deps if "views-transformation-library" in d]
    assert not offenders, (
        f"views-transformation-library is unused + redundant (pulled via "
        f"views-pipeline-core); remove from direct deps: {offenders}"
    )
