"""Falsification stubs — claim: "views-frames is 100% integrated (development)".

Generated by the /falsify audit (2026-06-24). Each test encodes the **strong**
reading of "100% integrated": that *every* data path in views-reporting consumes
views-frames as its contract, with no residual pipeline-core dataset / torch /
wandb coupling. They currently FAIL — that is the point: they document the
falsifications.

They are marked ``xfail(strict=False)`` so they do **not** break the (green) CI
suite while the gaps are known, documented debt. Each one flips to **xPASS**
(visible) when its gap closes — at which point drop the marker (or set
``strict=True``) to lock the property in. Every finding maps to an EXISTING
register entry (no new registration needed) — see the reasons.
"""

from __future__ import annotations

import pathlib
import re

import pytest

_REPO = pathlib.Path(__file__).resolve().parent.parent
_SRC = _REPO / "views_reporting"
_DOCS = _REPO / "documentation"


def test_p1_statistics_api_is_views_frames_only():
    # RESOLVED (C-114 / #113): the dataset-level statistics API (calculate_map/
    # calculate_hdi/calculate_hdi_map/report_hdi/compute_statistics/sample_predictions)
    # is retired — only the frame-native `*_frame` variants remain, which consume a
    # views_frames PredictionFrame. No pipeline-core `_ViewsDataset`/`get_subset_tensor`
    # on the stats path. (entity_metadata.py still type-hints private datasets — that's
    # the C-22 viewser tail; see P6.)
    text = (_SRC / "statistics" / "dataset_statistics.py").read_text()
    assert "_ViewsDataset" not in text, "dataset-level stats still typed on pipeline-core"
    assert "get_subset_tensor" not in text, "still pulls tensors from a pipeline-core dataset"


def test_p2_reconciliation_is_on_views_frames():
    # RESOLVED (#72 / Cluster B): the torch + pipeline-core-private reconciliation
    # subsystem is deleted from views-reporting. The live reconciler is
    # `views_frames_reconcile` (views-frames, numpy, parity-proven against the former
    # ForecastReconciler); pipeline-core consumes it via an injected Reconciler
    # protocol, wired in views-models. Reporting renders; it does not reconcile.
    assert not (_SRC / "reconciliation").exists(), (
        "views_reporting/reconciliation/ should be deleted (reconciliation now lives "
        "in views-frames as views_frames_reconcile)"
    )
    # And torch is gone from the package entirely (it rode in only on reconciliation).
    for path in _SRC.rglob("*.py"):
        assert "import torch" not in path.read_text(), f"{path} still imports torch"


def test_p3_evaluation_consumes_metricframe_not_render_time_wandb():
    # RESOLVED (B2 / C-108): the eval report renders from an injected MetricFrame
    # source (MetricFrameFileSource); the render-time wandb scrape — the
    # evaluation_run_resolver + WandbEvaluationSource — is deleted. ADR-018 fulfilled
    # on the eval side. (Was xfail while Phase 3 was pending.)
    templates = _SRC / "templates" / "reports"
    assert not (templates / "evaluation_run_resolver.py").exists(), (
        "evaluation_run_resolver.py should be deleted (render-time wandb scrape gone)"
    )
    for path in templates.rglob("*.py"):
        text = path.read_text()
        assert "wandb.Api()" not in text, f"{path.name} still scrapes wandb at render time"
        assert "import wandb" not in text, f"{path.name} still imports wandb"


def test_p5_governance_declares_integration_complete():
    # RESOLVED (B2 / C-108): ADR-018 no longer declares the EVALUATION inversion
    # incomplete — the self-deprecating "remains Phase 3" / "knowingly violates its
    # own ADR" language is gone now that the eval-metrics inversion is done end-to-end.
    # (The metadata/viewser-side acquisition — C-22 — is a separate, still-open strand;
    # this asserts only the eval-inversion confession is retired.)
    adr = (_DOCS / "ADRs" / "018_render_from_given_data.md").read_text()
    assert "remains Phase 3" not in adr
    assert "knowingly violates its own ADR" not in adr


@pytest.mark.xfail(
    strict=False,
    reason="P6: one holdout remains — `metadata/entity_metadata.py` TYPE_CHECKING-imports "
    "`_CDataset`/`_PGDataset`/`_ViewsDataset` on its dataset-keyed accessors. Those are "
    "the live-VIEWSER functions, so they retire with the C-22/#70 viewser sprint, not "
    "C-114. (reconciliation.py + the dataset-level stats API were removed by #72 / this "
    "C-114 sprint.) Tracked: C-114 / C-22.",
)
def test_p6_no_pipeline_core_private_internal_imports():
    pat = re.compile(r"import\s+.*\b_(?:C|PG|Views)Dataset\b")
    offenders = [
        str(p.relative_to(_REPO))
        for p in _SRC.rglob("*.py")
        if pat.search(p.read_text())
    ]
    assert not offenders, f"pipeline-core private-internal imports remain: {offenders}"
