"""Uniform-lattice contract (register C-208/C-209) — falsify stubs, promoted.

Generated by /falsify (2026-07-15) against the fix spec; xfail markers dropped
when the fix landed (repo convention). The Marion-class gapped lattice — a
coastal block + one isolated cell 12° south — is the regression fixture for:
(1) the raster budget keyed to the UNIFORM lattice size, not data rows;
(2) no hover popups on NaN ocean fill;
(3) PNG cells at TRUE coordinates (no even-spread misplacement), coastline-safe.
"""

from __future__ import annotations

import base64
import io
from unittest.mock import MagicMock, patch

import numpy as np
import pandas as pd
import pytest

try:
    from views_frames import PredictionFrame, SpatialLevel, SpatioTemporalIndex

    from views_reporting.mapping.mapping import (
        MappingModule,
        pgm_lattice_cell_frames,
    )
except ImportError:
    pytest.skip("views_frames not installed", allow_module_level=True)

TARGET = "pred_x"


def _pgm_module():
    mock_gdf = MagicMock()
    mock_gdf.columns = ["gid", "xcoord", "ycoord", "col", "row", "geometry"]
    with patch("views_reporting.mapping.mapping.gpd.read_file", return_value=mock_gdf):
        idx = SpatioTemporalIndex(
            time=np.array([528], dtype=np.int64),
            unit=np.array([1], dtype=np.int64),
            level=SpatialLevel.PGM,
        )
        return MappingModule(
            frame=PredictionFrame(np.array([[1.0]], dtype=np.float32), idx),
            level=SpatialLevel.PGM,
            target_column=TARGET,
        )


def _gapped_mdf(module, times=(528,)):
    """The Marion-class fixture: a coastal block + ONE isolated far-south cell."""
    coords = [(-34.75, 19.25), (-34.75, 19.75), (-34.25, 19.25), (-34.25, 19.75),
              (-46.75, 37.75)]  # the isolated cell, 12 degrees south
    rows = []
    for t in times:
        for i, (lat, lon) in enumerate(coords, start=1):
            rows.append({
                module._location_col: i, module._time_id: t, TARGET: float(i),
                "xcoord": lon, "ycoord": lat, "row": 0, "col": 0,
            })
    return pd.DataFrame(rows)


@pytest.mark.red_team
def test_raster_budget_is_keyed_to_lattice_size_not_data_rows():
    """C-209: 5 data rows spanning a 26×38 bounding box must be budgeted as the
    LATTICE (988 cell-frames), not the row count — sparse-but-spread data can
    no longer sail past the guard while the dense z explodes."""
    m = _pgm_module()
    mdf = _gapped_mdf(m)
    assert len(mdf) == 5
    assert pgm_lattice_cell_frames(mdf, m._time_id) == 26 * 38  # the real driver
    with pytest.raises(ValueError, match="lattice cell-frames"):
        m.plot_map(mdf, TARGET, interactive=True, as_html=True,
                   raster=True, max_raster_cell_frames=20)


@pytest.mark.green_team
def test_raster_filler_cells_have_no_hover():
    """C-208 (falsify F4): NaN ocean fill offers no hover popups."""
    m = _pgm_module()
    fig = m.plot_map(_gapped_mdf(m), TARGET, interactive=True, as_html=False,
                     raster=True)
    assert fig.data[0].hoverongaps is False


@pytest.mark.green_team
def test_raster_axes_are_uniform_and_bricks_true_sized():
    """C-208: the heatmap axes are UNIFORM 0.5° lattices spanning the extent —
    plotly's midpoint bricks are then exactly 0.5° everywhere; the Marion gap
    can no longer stretch coastal cells into the ocean."""
    m = _pgm_module()
    fig = m.plot_map(_gapped_mdf(m), TARGET, interactive=True, as_html=False,
                     raster=True)
    y = np.asarray(fig.data[0].y, dtype=float)
    x = np.asarray(fig.data[0].x, dtype=float)
    assert len(y) == 26 and len(x) == 38  # bounding box, not coords-in-data
    assert np.allclose(np.diff(y), 0.5) and np.allclose(np.diff(x), 0.5)
    # data lands at true positions: Marion's value (5.0) at its own coords only
    z = np.asarray(fig.data[0].z, dtype=float)
    hits = np.argwhere(np.isclose(z, np.log1p(5.0), rtol=1e-5))
    assert len(hits) == 1
    yi, xi = hits[0]
    assert (y[yi], x[xi]) == (-46.75, 37.75)


@pytest.mark.red_team
def test_png_places_gapped_lattice_cells_at_true_latitude():
    """C-208 (falsify F3, was a LIVE latent bug): imshow previously spread the
    row array evenly across the extent, smearing the coastal block over the top
    two-thirds of the image. Post-fix, saturated (orange/red) cells appear only
    near the top (coastal block) and bottom (Marion) — the 12° gap in between
    renders as EMPTY ocean, not stretched land."""
    m = _pgm_module()
    m._coastline_cache = (np.array([0.0, np.nan]), np.array([0.0, np.nan]))
    html = m._plot_image_map(_gapped_mdf(m), TARGET)
    png = base64.b64decode(html.split("base64,", 1)[1].split('"', 1)[0])
    import matplotlib.image as mpimg

    img = mpimg.imread(io.BytesIO(png))
    h = img.shape[0]
    # saturated warm cells: red well above blue (grey text/coastline has r≈b).
    # Exclude the colourbar by column SPAN: its warm strip covers most of the
    # image height, while any data cell covers only a sliver — cropping by a
    # fixed width would cut off Marion, which sits at the lattice's far right.
    warm_full = (img[..., 0] - img[..., 2]) > 0.15
    data_cols = warm_full.mean(axis=0) < 0.5
    warm = warm_full[:, data_cols]
    rows = np.where(warm.any(axis=1))[0]
    assert len(rows) > 0
    middle = warm[int(h * 0.30) : int(h * 0.70), :]
    # pre-fix: the even-spread coastal block covered ~2/3 of the image height,
    # so the middle band was full of warm pixels; post-fix it must be empty
    assert not middle.any(), "cells rendered inside the lattice gap (stretch/misplacement)"
    assert rows.min() < h * 0.30  # the coastal block, near the top
    assert rows.max() > h * 0.70  # Marion, near the bottom — at its TRUE latitude
