"""Packaging invariants surfaced by the hatchling+uv migration falsification audit.

These guard the build-tooling decisions (ADR-014, superseding ADR-013): the
Python-3.11-only cap, the Linux/macOS resolution scope, and the removal of the
unused `views-transformation-library` direct dependency. Generated by /falsify.
"""

import sys
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover
    import tomli as tomllib

PYPROJECT = Path(__file__).resolve().parent.parent / "pyproject.toml"


def _pyproject():
    return tomllib.loads(PYPROJECT.read_text())


def test_requires_python_capped_below_3_12():
    """3.12 and 3.13 cannot install: levenshtein 0.20.9 (pulled via
    views-pipeline-core -> ingester3) has no wheel and fails to build there.
    requires-python must keep the cap below 3.12 until upstream updates."""
    rp = _pyproject()["project"]["requires-python"].replace(" ", "")
    assert "<3.12" in rp, f"requires-python must cap below 3.12, got {rp!r}"


def test_resolution_scoped_to_linux_and_macos():
    """viewser -> docker -> pywin32 makes universal resolution fail on Windows.
    uv environments must scope to the supported platforms (Linux + macOS)."""
    envs = " ".join(_pyproject().get("tool", {}).get("uv", {}).get("environments", []))
    assert "linux" in envs and "darwin" in envs and "win32" not in envs, (
        f"uv environments must be scoped to linux+darwin, got {envs!r}"
    )


def test_no_unused_transformation_library_dependency():
    """FALSIFICATION P3: views-transformation-library is never imported in
    views_reporting and is already pulled transitively via views-pipeline-core,
    so it must not be a *direct* dependency. FAILS until the phantom dep is
    removed from pyproject and the lockfile regenerated."""
    deps = _pyproject()["project"]["dependencies"]
    offenders = [d for d in deps if "views-transformation-library" in d]
    assert not offenders, (
        f"views-transformation-library is unused + redundant (pulled via "
        f"views-pipeline-core); remove from direct deps: {offenders}"
    )
