"""Falsification stubs — claim: "views-frames is 100% integrated (development)".

Generated by the /falsify audit (2026-06-24). Each test encodes the **strong**
reading of "100% integrated": that *every* data path in views-reporting consumes
views-frames as its contract, with no residual pipeline-core dataset / torch /
wandb coupling. They currently FAIL — that is the point: they document the
falsifications.

They are marked ``xfail(strict=False)`` so they do **not** break the (green) CI
suite while the gaps are known, documented debt. Each one flips to **xPASS**
(visible) when its gap closes — at which point drop the marker (or set
``strict=True``) to lock the property in. Every finding maps to an EXISTING
register entry (no new registration needed) — see the reasons.
"""

from __future__ import annotations

import pathlib
import re

import pytest

_REPO = pathlib.Path(__file__).resolve().parent.parent
_SRC = _REPO / "views_reporting"
_DOCS = _REPO / "documentation"


@pytest.mark.xfail(
    strict=False,
    reason="P1: the dataset-level statistics API (calculate_map/calculate_hdi/"
    "calculate_hdi_map/report_hdi/compute_statistics/sample_predictions) still "
    "consumes pipeline-core `_ViewsDataset` + `get_subset_tensor`, in parallel to "
    "the frame-native *_frame variants. Tracked: ADR-018 Phase 2 / C-114.",
)
def test_p1_statistics_api_is_views_frames_only():
    text = (_SRC / "statistics" / "dataset_statistics.py").read_text()
    assert "_ViewsDataset" not in text, "dataset-level stats still typed on pipeline-core"
    assert "get_subset_tensor" not in text, "still pulls tensors from a pipeline-core dataset"


@pytest.mark.xfail(
    strict=False,
    reason="P2: the reconciliation subsystem is entirely on torch + pipeline-core "
    "`_CDataset`/`_PGDataset` + WandBModule — zero views-frames. Tracked: Cluster B, "
    "C-24 (torch), GitHub #72 (move to views-postprocessing).",
)
def test_p2_reconciliation_is_on_views_frames():
    text = (_SRC / "reconciliation" / "reconciliation.py").read_text()
    assert "import torch" not in text, "reconciliation still uses torch"
    assert "_CDataset" not in text and "_PGDataset" not in text, (
        "reconciliation still typed on pipeline-core private datasets"
    )


@pytest.mark.xfail(
    strict=False,
    reason="P3: the evaluation report path acquires metrics via wandb at render "
    "time (`wandb.Api()`), not via an injected views-frames `MetricFrame`. "
    "Tracked: Cluster A root C-108, C-48, ADR-018 Phase 3 (MetricFrame) pending.",
)
def test_p3_evaluation_consumes_metricframe_not_render_time_wandb():
    text = (_SRC / "templates" / "reports" / "evaluation_run_resolver.py").read_text()
    assert "wandb.Api()" not in text, "eval still scrapes wandb at render time"


@pytest.mark.xfail(
    strict=False,
    reason="P5: the repo's OWN governance declares the integration incomplete — "
    "ADR-018 says the MetricFrame/eval inversion 'remains Phase 3' and the package "
    "'knowingly violates its own ADR'. The '100%' claim contradicts the docs.",
)
def test_p5_governance_declares_integration_complete():
    adr = (_DOCS / "ADRs" / "018_render_from_given_data.md").read_text()
    assert "remains Phase 3" not in adr
    assert "knowingly violates its own ADR" not in adr


@pytest.mark.xfail(
    strict=False,
    reason="P6: views_reporting imports pipeline-core PRIVATE internals "
    "(`_CDataset`/`_PGDataset`/`_ViewsDataset`), incl. a runtime import in "
    "reconciliation.py. Tracked: C-114.",
)
def test_p6_no_pipeline_core_private_internal_imports():
    pat = re.compile(r"import\s+.*\b_(?:C|PG|Views)Dataset\b")
    offenders = [
        str(p.relative_to(_REPO))
        for p in _SRC.rglob("*.py")
        if pat.search(p.read_text())
    ]
    assert not offenders, f"pipeline-core private-internal imports remain: {offenders}"
