"""
CIC coverage for ReportModule.

Tests content accumulation, HTML generation, and table splitting.
Mocks PipelineConfig to avoid views_pipeline_core dependency.
"""

from unittest.mock import patch

import pandas as pd
import pytest

try:
    from views_reporting.reports.report import ReportModule
except ImportError:
    pytest.skip(
        "views_pipeline_core not installed",
        allow_module_level=True,
    )


# ── Green team: content accumulation ─────────────────────────────────────


@pytest.mark.green_team
class TestContentAccumulation:

    def test_constructor_adds_header_image(self):
        report = ReportModule()
        assert len(report.content) == 1
        assert "data:image/" in report.content[0]

    def test_add_heading_h1(self):
        report = ReportModule()
        report.add_heading("Test Title", level=1)
        assert any("<h1" in c for c in report.content)

    def test_add_heading_h2(self):
        report = ReportModule()
        report.add_heading("Subtitle", level=2)
        assert any("<h2" in c for c in report.content)

    def test_add_paragraph(self):
        report = ReportModule()
        report.add_paragraph("Hello world")
        assert any("Hello world" in c for c in report.content)
        assert any("<p" in c for c in report.content)

    def test_add_table_dict(self):
        report = ReportModule()
        report.add_table({"key1": "val1", "key2": "val2"})
        assert any("<table" in c for c in report.content)

    def test_add_table_dataframe(self):
        report = ReportModule()
        df = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
        report.add_table(df)
        assert any("<table" in c.lower() for c in report.content)

    def test_add_table_invalid_type_raises(self):
        report = ReportModule()
        with pytest.raises(TypeError, match="DataFrame or dictionary"):
            report.add_table("not a table")


# ── Green team: table splitting ──────────────────────────────────────────


@pytest.mark.green_team
class TestTableSplitting:

    def test_large_dataframe_splits_by_rows(self):
        report = ReportModule()
        df = pd.DataFrame({"A": range(20), "B": range(20)})
        report.add_table(df, split_threshold=8)
        html = "\n".join(report.content)
        assert "split-table-container" in html or html.count("<table") >= 2

    def test_small_dataframe_no_split(self):
        report = ReportModule()
        df = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
        report.add_table(df)
        html = "\n".join(report.content)
        assert "split-table-container" not in html


# ── Beige team: export workflow ──────────────────────────────────────────


@pytest.mark.beige_team
class TestExportWorkflow:

    def test_export_creates_valid_html(self, tmp_path):
        with patch(
            "views_reporting.reports.report.PipelineConfig"
        ) as mock_config:
            mock_config.current_version = "0.0.0-test"

            report = ReportModule()
            report.add_heading("Test Report")
            report.add_paragraph("Content here")
            report.add_table({"metric": "value"})

            out = tmp_path / "test_report.html"
            report.export_as_html(str(out))

            assert out.exists()
            html = out.read_text()
            assert "<!DOCTYPE html>" in html
            assert "Test Report" in html
            assert "Content here" in html

    def test_export_with_footer(self, tmp_path):
        with patch(
            "views_reporting.reports.report.PipelineConfig"
        ) as mock_config:
            mock_config.current_version = "0.0.0-test"

            report = ReportModule()
            report.add_footer("Generated by test")

            out = tmp_path / "footer_report.html"
            report.export_as_html(str(out))

            html = out.read_text()
            assert "Generated by test" in html
